name: Build and Test PRs on DeepStack Dev Branch
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Fetch GIT LFS
      run: git lfs checkout
    - name: Setup Golang
      uses: actions/setup-go@v2
    - name: Setup Powershell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo add-apt-repository universe
        sudo apt-get install -y powershell
    - name: Build DeepStack Go Component
      run: cd server && go build
    - name: Build DeepStack CPU Version
      run: sudo docker build -t deepquestai/deepstack:cpu . -f Dockerfile.cpu
    - name: Run DeepStack
      run: sudo docker run -d --name deepstack -e VISION-FACE=True -e VISION-SCENE=True -e VISION-DETECTION=True -p 80:5000 deepquestai/deepstack:cpu
    - name: Run Tests
      run: pwsh -Command ".\tests.ps1 -DeepStackURL 'http://localhost:80'"
