name: Build, Test And Publish DeepStack on Main Branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  publish:
    name: Deploy to Live Docs Server
    needs: build
    runs-on: ubuntu-latest
    steps: